development:
  adapter: postgresql
  database: test_steam_api_development
  host: localhost
  user: postgres
  password: pg

test:
  adapter: postgresql
  database: test_steam_api_test
  host: localhost
  user: postgres
  password: pg

